repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.6
    hooks:
      - id: ruff
        args: [--fix, --unsafe-fixes]
      - id: ruff
        args: [--select, I, --fix]
      - id: ruff-format