version: '3.8'

services:
  pokemon-tcg-bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: pokemon-tcg-bot
    container_name: pokemon-tcg-bot
    working_dir: /app  
    command: ["python", "-m", "bot.start_bot"]
    volumes:
      - ./bot:/app/bot
    env_file:
      - .env
    depends_on:
      liquibase:
        condition: service_completed_successfully

  liquibase:
    image: liquibase/liquibase:4.23.1
    container_name: liquibase
    entrypoint: ["liquibase", "--logLevel=info", "update"]
    volumes:
      - ./liquibase/changelog:/liquibase/changelog
    depends_on:
      - postgres
    restart: "no"
    env_file:
      - .env
    environment:
      LIQUIBASE_COMMAND_CHANGELOG_FILE: changelog/db.changelog-master.yaml
      LIQUIBASE_COMMAND_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      LIQUIBASE_COMMAND_USERNAME: ${POSTGRES_USER}
      LIQUIBASE_COMMAND_PASSWORD: ${POSTGRES_PASSWORD}

  postgres:
    image: postgres:16
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  postgres_data: