version: '3.8'

services:
  pokemon-tcg-bot:
    image: pokemon-tcg-bot
    container_name: pokemon-tcg-bot
    working_dir: /app  
    command: ["python", "-m", "bot.start_bot"]
    volumes:
      - ./bot:/app/bot
    env_file:
      - .env
    depends_on:
      - postgres
      - postgres-init

  postgres:
    image: postgres:16
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpwd
      POSTGRES_DB: player_db
    volumes:
      - player_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD", "sh", "-c", "pg_isready -U testuser -d player_db"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  postgres-init:
    image: postgres-init:latest
    container_name: postgres-init
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpwd
      POSTGRES_DB: player_db
    restart: "no"

volumes:
  player_data: