version: '3'

services:
  pokemon-tcg-bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./bot:/app/bot
    env_file:
      - .env
    image: pokemon-tcg-bot
    container_name: pokemon-tcg-bot
    working_dir: /app  
    command: ["python", "-m", "bot.start_bot"] 

  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    container_name: postgres

volumes:
  postgres_data: