version: '3'

services:
  pokemon-tcg-bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./bot:/app/bot
    env_file:
      - .env
    image: pokemon-tcg-bot
    container_name: pokemon-tcg-bot